--- 
javascripts: 
- snorby: 
  - jquery
  - jquery-ui
  - rails
  - hotkeys
  - mustache
  - easing
  - tipsy
  - fancybox
  - growl
  - colorpicker
  - editable
  - hint
  - scrollto
  - snorby
stylesheets: 
- snorby: 
  - grid
  - snorby
