snorby: &snorby
  adapter: mysql
  username: root
  password: s3cr3tsauce
  host: localhost

development:
  database: snorby
  <<: *snorby

test:
  database: snorby
  <<: *snorby

production:
  database: snorby
  <<: *snorby
