defaults: &defaults
  adapter: mysql
  # encoding: utf8
  # collation: utf8_general_ci
  username: root
  password: s3cr3tsauce
  host: localhost

development:
  database: snorby
  <<: *defaults
test:
  database: snorby
  <<: *defaults
production:
  database: snorby
  <<: *defaults
