# Snorby Database Configuration
#
# Please set your database password/user below
#
snorby: &snorby
  adapter: mysql
  username: root
  password: database_password_here
  host: localhost

development:
  database: snorby
  <<: *snorby

test:
  database: snorby
  <<: *snorby

production:
  database: snorby
  <<: *snorby
