development:
  domain: localhost:3000
  mailer_address: 'snorby@example.com'

test:
  domain: localhost:3000
  mailer_address: 'snorby@example.com'

production:
  domain: mephux.gotdns.com:8080
  mailer_address : 'snorby@example.com'
