development:
  domain: localhost:3000
  mailer_address: 'snorby@example.com'

test:
  domain: test.host
  mailer_address: 'snorby@example.com'

production:
  domain: example.com
  mailer_address : 'snorby@example.com'
