development:
  domain: localhost:3000
  wkhtmltopdf: /usr/local/bin/wkhtmltopdf

test:
  domain: localhost:3000
  wkhtmltopdf: /usr/local/bin/wkhtmltopdf

# You Should Only Need To Set This Option
# Example: localhost:3000
production:
  domain: localhost:3000
  wkhtmltopdf: /usr/local/bin/wkhtmltopdf
