development:
  domain: localhost:3000
  wkhtmltopdf: /usr/local/bin/wkhtmltopdf
  #wkhtmltopdf: /Users/mephux/.rvm/gems/ruby-1.9.2-p0/bin/wkhtmltopdf

test:
  domain: localhost:3000
  wkhtmltopdf: /usr/local/bin/wkhtmltopdf

production:
  domain: localhost:3000
  wkhtmltopdf: /usr/local/bin/wkhtmltopdf